//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ICQ Clan.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ICQCLAN_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_DEFAULT_SERVEUR             104
#define IDD_REG_NEW                     106
#define IDD_REG_WELCOME                 107
#define IDR_MAINFRAME                   128
#define IDD_NEWUSER_DIALOG              130
#define IDD_OLDUSER_DIALOG              132
#define IDI_STATE_NA                    133
#define IDI_STATE_ONLINE                134
#define IDI_STATE_AWAY                  136
#define IDI_STATE_BUSY                  137
#define IDI_STATE_INVISIBLE             138
#define IDI_STATE_OFFLINE               139
#define IDI_STATE_WANNAPLAY             140
#define IDI_PLAYING_HL                  142
#define IDC_LIEN                        143
#define IDR_POPUP_MENU                  146
#define IDR_MAIN_MENU                   147
#define IDD_CLANDETAILS_DIALOG          152
#define IDD_USERDETAILS_DIALOG          153
#define IDD_SEND_DIALOG                 154
#define IDD_RECEIVE_DIALOG              155
#define IDI_MSG                         156
#define IDR_MENU1                       158
#define IDD_OPTIONS_MENU                165
#define IDD_OPTIONS_GENERAL             167
#define IDD_OPTIONS_SKIN                168
#define IDD_REG_OLD                     169
#define IDB_WIZARD                      171
#define IDB_OPTIONS                     172
#define IDR_AVI_WBC                     174
#define IDB_MYDETAILS                   175
#define IDR_AVI_ICQ                     176
#define IDD_MYDETAILS_DIALOG            177
#define IDD_OPTIONS_SECURITY            179
#define IDD_ENTERPWD_DIALOG             181
#define IDD_OPTIONS_GAME                182
#define IDB_MAINMENU                    183
#define IDB_MAINMENU_HELP               184
#define IDB_MAINMENU_ABOUT              185
#define IDB_MAINMENU_OPTIONS            186
#define IDB_MAINMENU_USER               187
#define IDB_MAINMENU_TRAY               188
#define IDB_MAINMENU_DELCLAN            189
#define IDB_MAINMENU_DELUSER            190
#define IDB_MAINMENU_CLANDETAILS        191
#define IDB_MAINMENU_LEADER             192
#define IDB_MAINMENU_CREATECLAN         193
#define IDD_ADDCLAN_DIALOG              195
#define IDS_ERRORS                      1000
#define IDC_ADD_BUTTON                  1001
#define IDS_OLD_USER_1                  1001
#define IDC_MAIN_BUTTON                 1002
#define IDS_ADD_CLAN_1                  1002
#define IDC_SYS_BUTTON                  1003
#define IDC_STATUS_COMBO                1004
#define IDS_ADD_CLAN_3                  1004
#define IDC_BUTTON1                     1005
#define IDS_ADD_CLAN_4                  1005
#define IDC_BUTTON2                     1006
#define IDS_WRONGPWD_1                  1006
#define IDC_NICK_EDIT                   1008
#define IDC_NAME_EDIT                   1009
#define IDC_FIRSTNAME_EDIT              1010
#define IDC_CIN_EDIT                    1010
#define IDC_PWD_EDIT                    1011
#define IDC_PWD_EDIT2                   1012
#define IDC_UIN_EDIT                    1013
#define IDC_OLDPWD_EDIT                 1014
#define IDC_WEB_EDIT                    1018
#define IDC_ICQ_EDIT                    1019
#define IDC_EMAIL_EDIT                  1020
#define IDC_CLAN_EDIT                   1026
#define IDC_LEADER_EDIT                 1029
#define IDC_TXT_EDIT                    1033
#define IDC_CLAN_STATIC                 1035
#define IDC_GRPBOX_STATIC               1036
#define IDC_ALWAYSTOP_CHECK             1037
#define IDC_SERVER_EDIT                 1038
#define IDC_MENU                        1039
#define IDC_MENU_SPEED2_EDIT            1039
#define IDC_PORT_EDIT                   1039
#define IDC_MENU_RATE_EDIT              1040
#define IDC_SKIN_BUTTON                 1042
#define IDC_MENU_CLOSEONEXIT_CHECK      1043
#define IDC_AUTOR_EDIT                  1043
#define IDC_MENU_SPEED1_EDIT            1044
#define IDC_NFO_EDIT                    1044
#define IDC_NEW_RADIO                   1047
#define IDC_OLD_RADIO                   1048
#define IDC_PWD2_EDIT                   1049
#define IDC_1_STATIC                    1051
#define IDC_0_STATIC                    1052
#define IDC_BUILD_TEXT                  1052
#define IDC_2_STATIC                    1053
#define IDC_3_STATIC                    1054
#define IDC_4_STATIC                    1055
#define IDC_5_STATIC                    1056
#define IDC_ANIMATE1                    1057
#define IDC_ANIMATE2                    1058
#define IDC_SAVEPWD_CHECK               1059
#define IDC_IP_CHECK                    1062
#define IDC_HL_EDIT                     1064
#define IDC_HL_BUTTON                   1065
#define IDC_Q3_EDIT                     1066
#define IDC_INPUTSTR_EDIT               1066
#define IDC_Q3_BUTTON                   1067
#define IDC_INPUTNUM_EDIT               1067
#define ID_SRVPORT                      6002
#define ID_OPENICQCLAN                  32772
#define ID_MINIMIZEICQCLAN              32773
#define ID_MAINMENU_SHUTDOWN            32775
#define ID_MAINMENU_USERINFOS           32777
#define ID_MAINMENU_OPTIONS             32778
#define ID_MAINMENU_HELP_ABOUT          32779
#define ID_MAINMENU_CEATEACLAN          32780
#define ID_MAINMENU_CLANLEADEROPTIONS_DELETETHECLAN 32782
#define ID_MAINMENU_CLANLEADEROPTIONS_CLANDETAILS 32784
#define ID_MAINMENU_CLANLEADEROPTIONS_KICKCLANUSER 32785
#define ID_USERCONTECTMENU_SENDAMESSAGE 32786
#define ID_USERCONTECTMENU_JOINTHEGAME  32787
#define IDC_LBL                         65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
